<!doctype html>
<html lang="pt_br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="../../public/node_modules/bootstrap/compiler/bootstrap.css" rel="stylesheet">

    <link href="../../public/css/style.css" rel="stylesheet">
    <link href="../../public/css/navbar.css" rel="stylesheet">
    <link href="../../public/css/menu.css" rel="stylesheet">

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <title>Marked</title>
  </head>
  <body>
    
    <input type="checkbox" id="check">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="log-men">
            <label for="check">
              <img src="../../public/img/menu.svg" id="btn"/>
            </label>
            <a href="indexMarked">
              <img src="../../public/img/logomarked.svg" class="img-fluid" alt="Marked">
            </a>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSite">
            <form class="form-inline mx-auto" >
              <input class="form-contro" type="search" placeholder="⠀Pesquisar...">
              <button class="btn btn-secondary" type="submit">ok</button>
            </form>

            <a href="safebox">
              <img src="../../public/img/pig.svg" class="pig" alt="Cofre">
            </a>

          </div>
        </div>
      </nav>

      <div class="sidebar">
        <header><div class="image"></div>Olá, <?=$user['nome']?></header>
        <ul>
          <li><a href="http://localhost:8080/myrequests"><img class="icon" src="../../public/img/myrequests.png">⠀Meus pedidos</a></li>
          <li><a href="http://localhost:8080/make_order"><img class="icon" src="../../public/img/makeorder.png">⠀Fazer Pedido</a></li>
          <li><a href="http://localhost:8080/notifications"><img class="icon" src="../../public/img//notification.png">⠀Notificações</a></li>
          <li><a href="http://localhost:8080/profile"><img class="icon" src="../../public/img/myprofile.png">⠀Meu perfil</a></li>
          <li><a href="http://localhost:8080/helpcenter"><img class="icon" src="../../public/img/helpcenter.png">⠀Central de ajuda</a></li>
          <li><a href="http://localhost:8080/about_us"><img class="icon" src="../../public/img/aboutus.png">⠀Sobre nós</a></li>
          <li><a href="http://localhost:8080/terms_of_use"><img class="icon" src="../../public/img/termsofuse.png">⠀Termos de uso</a></li>
          <li><a href="http://localhost:8080/login/logout"><img class="icon" src="../../public/img/logoff.svg">⠀Sair</a></li>
        </ul>
      </div>

      <div id="carouselSite" class="carousel slide" data-ride="carousel">

        <ol class="carousel-indicators">
          <li data-target="carouselSite" data-slide-to="0" class="active"></li>
          <li data-target="carouselSite" data-slide-to="1"></li>
          <li data-target="carouselSite" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="../../public/img/belkin-wireless-charging-banner-architect-v01-r01-1680x500-us(1).jpg" class="image-fluid d-block" alt="img1">
          </div>
          <div class="carousel-item">
            <img src="../../public/img/belkin-wireless-charging-banner-planner-v02-r01-1680x500-us(1).jpg" class="image-fluid d-block" alt="img2">
          </div>
          <div class="carousel-item">
            <img src="../../public/img/thunderbolt-banr-1680x500.jpg" class="image-fluidd-block" alt="img3">
          </div>
        </div>

        <a class="carousel-control-prev" href="#carouselSite" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon"></span>
          <span class="sr-only">aa</span>
        </a>

        <a class="carousel-control-next" href="#carouselSite" role="button" data-slide="next">
          <span class="carousel-control-next-icon"></span>
          <span class="sr-only">aa</span>
        </a>
      </div>

      <div class="container">

        <h1 class="font-weight-light text-center text-lg-center mt-4 mb-0">Pedidos por categoria</h1>
      
        <hr class="mt-2 mb-5">
      
        <div class="row text-center text-lg-left">
      
          <div class="col-lg-3 col-md-4 col-6">
            <p>Notebooks</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="w-60 img-thumbnail" src="../../public/img/notebook.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Monitores</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-60 img-thumbnail" src="../../public/img/monitor.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Computadores</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-60 img-thumbnail" src="../../public/img/pc.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Carregadores</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-60 img-thumbnail" src="../../public/img/carregador.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Fios</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-60 img-thumbnail" src="../../public/img/fios.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Headsets</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-60 img-thumbnail" src="../../public/img/headset.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Eletrodomésticos</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-60 img-thumbnail" src="../../public/img/eletrodomesticos.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Jogos</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-60 img-thumbnail" src="../../public/img/jogos.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Tablets</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-60 img-thumbnail" src="../../public/img/tablet.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Áudios</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-60 img-thumbnail" src="../../public/img/audio.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Drones e acessórios</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-60 img-thumbnail" src="../../public/img/drone.jpg" alt="">
                </a>
          </div>
          <div class="col-lg-3 col-md-4 col-6">
            <p>Outros</p>
            <a href="#" class="d-block mb-4 h-100">
                  <img class="m-50 img-thumbnail" src="../../public/img/outros.jpg" alt="">
                </a>
          </div>
        </div>
      
      </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="../../public/node_modules/jquery/dist/jquery.js"></script>
    <script src="../../public/node_modules/popper.js/dist/umd/popper.js"></script>
    <script src="../../public/node_modules/bootstrap/dist/js/bootstrap.js"></script>
    
  </body>
</html>