<!doctype html>
<html lang="pt_br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="../../public/node_modules/bootstrap/compiler/bootstrap.css" rel="stylesheet">

    <link href="../../public/css/navbar.css" rel="stylesheet">
    <link rel="stylesheet" href="../../public/css/make_order.css">
    <link href="../../public/css/menu.css" rel="stylesheet">

    <title>Marked</title>
  </head>
  <body>

    <input type="checkbox" id="check">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="log-men">
            <label for="check">
              <img src="../../public/img/menu.svg" id="btn"/>
            </label>
            <a href="indexMarked">
              <img src="../../public/img/logomarked.svg" class="img-fluid" alt="Marked">
            </a>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSite">
            <form class="form-inline mx-auto" >
              <input class="form-contro" type="search" placeholder="⠀Pesquisar...">
              <button class="btn btn-secondary" type="submit">ok</button>
            </form>

            <a href="safebox">
              <img src="../../public/img/pig.svg" class="pig" alt="Cofre">
            </a>
          </div>
        </div>
      </nav>
      
      <div class="sidebar">
        <header><div class="image"></div>Olá, <?=$user['user_name']?></header>
        <ul>
        <li><a href="myrequests"><img class="icon" src="../../public/img/myrequests.png">⠀Meus pedidos</a></li>
          <li><a href="make_order"><img class="icon" src="../../public/img/makeorder.png">⠀Fazer Pedido</a></li>
          <li><a href="notifications"><img class="icon" src="../../public/img/notification.png">⠀Notificações</a></li>
          <li><a href="profile"><img class="icon" src="../../public/img/myprofile.png">⠀Meu perfil</a></li>
          <li><a href="helpcenter"><img class="icon" src="../../public/img/helpcenter.png">⠀Central de ajuda</a></li>
          <li><a href="about_us"><img class="icon" src="../../public/img/aboutus.png">⠀Sobre nós</a></li>
          <li><a href="terms_of_use"><img class="icon" src="../../public/img/termsofuse.png">⠀Termos de uso</a></li>
          <li><a href="http://localhost:8080/login/logout"><img class="icon" src="../../public/img/logoff.svg">⠀Sair</a></li>
        </ul>
      </div>

      <?php if(isset($get)){ ?>
        
          <h1 class="title">Fazer pedido</h1>

          <p class="alert">Adicione uma foto ou imagem ilustrativa do que deseja</p>

          <form action="/make_order" method="POST" enctype="multipart/form-data">

            <div class="cont">
              <div class="img-cont">
                <img id="img" class="img" alt="Adicione uma imagem">
              </div>
              
              <div class="quest">
                <input class="upload" type='file' name="imagem" onchange="readURL(this);"/>

                <div class="mb-3">
                  <label class="form-label">Nome do produto</label>
                  <input type="text" class="form-control" id="name" name="nome_produto" 
                  placeholder="Ex: Gravador de som">
                </div>

                <div class="mb-3">
                  <label for="inputQuestion">Categoria</label>
                  <select id="inputQuestion" name="categoria" class="form-control">
                    <option selected>Notebooks</option>
                    <option>Monitores</option>
                    <option>Computadores</option>
                    <option>Fios</option>
                    <option>Headsets</option>
                    <option>Eletrodomésticos</option>
                    <option>Jogos</option>
                    <option>Tablets</option>
                    <option>Áudios</option>
                    <option>Drones e acessórios</option>
                    <option>Outros</option>
                  </select>
                </div>

                <div class="form-group">
                  <label for="exampleFormControlTextarea1">Descrição</label>
                  <textarea class="form-control" name="descricao" id="exampleFormControlTextarea1" rows="3" placeholder="Ex: Gravador de som, preto e semi-novo."></textarea>
                </div>

                <div class="mb-3">
                  <label class="form-label">Preço disposto a pagar (frete não incluso)</label>
                  <input type="text" class="form-control" name="preco" id="qtd">
                </div>
                <span>Obs: um preço justo, fará com que mais vendedores venham até você</span>
                
                 
                
                <div class="center">
                    <button type="submit" class="btn btn-primary">Confirmar pedido</button>
                </div>
              </div>
            </div>
          </form>
      </div>

<?php } else { ?>

      

      <div>
          <h1 class="title">Fazer pedido</h1>

          <p class="alert">Adicione uma foto ou imagem ilustrativa do que deseja</p>

          <form action="/make_order" method="POST" enctype="multipart/form-data">

            <div class="cont">
              <div class="img-cont" id="img-container">
                <img src="" id="preview" class="img" alt="Adicione uma imagem">
              </div>
              
              <div class="quest">
                <input class="upload" id="img" type='file' name="imagem" onchange="readURL(this)"/>

                <div class="mb-3">
                  <label class="form-label">Nome do produto</label>
                  <input type="text" class="form-control" id="name" name="nome_produto" 
                  placeholder="Ex: Gravador de som" value="<?=$array['nome_produto']?>">
                </div>

                <div class="mb-3">
                  <label for="inputQuestion">Categoria</label>
                  <select id="inputQuestion" name="categoria" class="form-control">
                    <option selected>Notebooks</option>
                    <option>Monitores</option>
                    <option>Computadores</option>
                    <option>Fios</option>
                    <option>Headsets</option>
                    <option>Eletrodomésticos</option>
                    <option>Jogos</option>
                    <option>Tablets</option>
                    <option>Áudios</option>
                    <option>Drones e acessórios</option>
                    <option>Outros</option>
                  </select>
                </div>

                <div class="form-group">
                  <label for="exampleFormControlTextarea1">Descrição</label>
                  <textarea class="form-control" name="descricao" id="exampleFormControlTextarea1" rows="3" 
                   placeholder="Ex: Gravador de som, preto e semi-novo." ><?=$array['descricao']?></textarea>
                </div>

                <div class="mb-3">
                  <label class="form-label">Preço disposto a pagar (frete não incluso)</label>
                  <input type="text" class="form-control" name="preco" id="qtd" value="<?=$array['preco']?>" >
                </div>
                <span>Obs: um preço justo, fará com que mais vendedores venham até você</span>
                
                  <?php if(isset($erro)){ ?>
                      <b style="text-align:center"> <?=$erro?> </b>
                  <?php } ?>
                
                <div class="center">
                    <button type="submit" class="btn btn-primary">Confirmar pedido</button>
                </div>
              </div>
            </div>
          </form>
      </div>

      <script>
        function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#img').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
            }
        }
      </script>
      
<?php } ?>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="../../public/node_modules/jquery/dist/jquery.js"></script>
    <script src="../../public/node_modules/popper.js/dist/umd/popper.js"></script>
    <script src="../../public/node_modules/bootstrap/dist/js/bootstrap.js"></script>
    
  </body>
</html>