<!doctype html>
<html lang="pt_br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="../../public/node_modules/bootstrap/compiler/bootstrap.css" rel="stylesheet">

    <link href="../../public/css/navbar.css" rel="stylesheet">
    <link rel="stylesheet" href="../../public/css/make_proposal.css">
    <link href="../../public/css/menu.css" rel="stylesheet">

    <title>Marked</title>
  </head>
  <body>
    <script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous">
    </script>

    <input type="checkbox" id="check">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="log-men">
            <label for="check">
              <img src="../../public/img/menu.svg" id="btn"/>
            </label>
            <a href="indexMarked">
              <img src="../../public/img/logomarked.svg" class="img-fluid" alt="Marked">
            </a>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSite">
            <form class="form-inline mx-auto" >
              <input class="form-contro" type="search" placeholder="⠀Pesquisar...">
              <button class="btn btn-secondary" type="submit">ok</button>
            </form>

            <a href="safebox">
              <img src="../../public/img/pig.svg" class="pig" alt="Cofre">
            </a>

          </div>
        </div>
      </nav>

      <div class="sidebar">
        <header><div class="image"></div>Olá, ...</header>
        <ul>
          <li><a href="myrequests"><img class="icon" src="../../public/img/myrequests.png">⠀Meus pedidos</a></li>
          <li><a href="make_order"><img class="icon" src="../../public/img/makeorder.png">⠀Fazer Pedido</a></li>
          <li><a href="notifications"><img class="icon" src="../../public/img/notification.png">⠀Notificações</a></li>
          <li><a href="profile"><img class="icon" src="../../public/img/myprofile.png">⠀Meu perfil</a></li>
          <li><a href="helpcenter><img class="icon" src="../../public/img/helpcenter.png">⠀Central de ajuda</a></li>
          <li><a href="about_us"><img class="icon" src="../../public/img/aboutus.png">⠀Sobre nós</a></li>
          <li><a href="terms_of_use"><img class="icon" src="../../public/img/termsofuse.png">⠀Termos de uso</a></li>
          <li><a href="http://localhost:8080/login/logout"><img class="icon" src="../../public/img/logoff.svg">⠀Sair</a></li>
        </ul>
      </div>
      <?php if(isset($array)){ ?>
        <div>
          <h1 class="title">Fazer proposta</h1>

          <form action="/make_proposal/insert" method="POST" enctype="multipart/form-data">
            
            <div class="cont">
              <div class="img-cont" style="width:420px; height:250px">
                <img  id="img" alt="Adicione uma imagem" name="imagem" style="width:420px; height:250px; text-align:center">
              </div>
              
              <div class="quest">
                <input type='file' id="upload" name="imagem">
                
                <div class="mb-3">
                <br>
                
                  <label class="form-label">Nome do produto</label>
                  <input type="text" class="form-control" id="name" name="nome_produto" value="<?=$array['nome_produto']?>">
                </div>

                <div class="mb-3">
                <br>
                  <label for="inputQuestion">Categoria</label>
                  <select id="inputQuestion" class="form-control" name="categoria">
                    <option selected>Notebooks</option>
                    <option>Monitores</option>
                    <option>Computadores</option>
                    <option>Fios</option>
                    <option>Headsets</option>
                    <option>Eletrodomésticos</option>
                    <option>Jogos</option>
                    <option>Tablets</option>
                    <option>Áudios</option>
                    <option>Drones e acessórios</option>
                    <option selected><?=$array['categoria']?></option>
                  </select>
                </div>

                <div class="mb-3">
                  <label class="form-label">Preço</label>
                  <input type="text" class="form-control" name="preco" id="price">
                </div>

                <div class="mb-3">
                  <label class="form-label">Quantidade</label>
                  <input type="text" class="form-control" name="quantidade" id="qtd">
                </div>

            


              <div class="col-md-6">
               
                <?php if(isset($erro)){ ?>
                      <b style="text-align:center"> <?=$erro?> </b>
                  <?php } ?>
                
              </div>
                
                
                <div class="center">
                  <br>  
                  <button type="submit" class="btn btn-primary" name="id_order" 
                  value="<?=$array['id_order']?>">Enviarrr</button>
                </div>
              
            </div>
          </form>
      </div>
      <?php }else{ ?>
      <div>
          <h1 class="title">Fazer proposta</h1>

          <form action="/make_proposal/insert" method="POST" enctype="multipart/form-data">
            
            <div class="cont">
              <div class="img-cont" style="width:420px; height:250px">
                <img  id="img" alt="Adicione uma imagem" name="imagem" style="width:420px; height:250px; text-align:center">
              </div>
              
              <div class="quest">
                <input type='file' id="upload" name="imagem">
                
                <div class="mb-3">
                <br>
                
                  <label class="form-label">Nome do produto</label>
                  <input type="text" class="form-control" id="name" name="nome_produto" value="<?=$order['order_name']?>">
                </div>

                <div class="mb-3">
                <br>
                  <label for="inputQuestion">Categoria</label>
                  <select id="inputQuestion" class="form-control" name="categoria">
                    <option selected>Notebooks</option>
                    <option>Monitores</option>
                    <option>Computadores</option>
                    <option>Fios</option>
                    <option>Headsets</option>
                    <option>Eletrodomésticos</option>
                    <option>Jogos</option>
                    <option>Tablets</option>
                    <option>Áudios</option>
                    <option>Drones e acessórios</option>
                    <option selected><?=$order['categories']?></option>
                  </select>
                </div>

                <div class="mb-3">
                  <label class="form-label">Preço</label>
                  <input type="text" class="form-control" name="preco" id="price">
                </div>

                <div class="mb-3">
                  <label class="form-label">Quantidade</label>
                  <input type="text" class="form-control" name="quantidade" id="qtd">
                </div>

            


              <div class="col-md-6">
               
                      
                <div class="center">
                  <br>  
                  <button type="submit" class="btn btn-primary" name="id_order" 
                  value="<?=$order['id_order']?>">Enviar1</button>
                </div>
              
            </div>
          </form>
      </div>
    <?php } ?>
      <script>
        $(function(){
            $('#upload').change(function(){
                
                const file = $(this)[0].files[0]
                const fileReader = new FileReader()
                fileReader.onloadend = function(){
                    $('#img').attr('src',fileReader.result)
                }
                fileReader.readAsDataURL(file)
            })
        })
    </script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="node_modules/jquery/dist/jquery.js"></script>
    <script src="node_modules/popper.js/dist/umd/popper.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.js"></script>
    
  </body>
</html>