<!doctype html>
<html lang="pt_br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="../../public/node_modules/bootstrap/compiler/bootstrap.css" rel="stylesheet">

    <link href="../../public/css/navbar.css" rel="stylesheet">
    <link rel="stylesheet" href="../../public/css/myrequests.css">
    <link href="../../public/css/menu.css" rel="stylesheet">

    <title>Marked</title>
  </head>
  <body>

    <input type="checkbox" id="check">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="log-men">
            <label for="check">
              <img src="../../public/img/menu.svg" id="btn"/>
            </label>
            <a href="indexMarked">
              <img src="../../public/img/logomarked.svg" class="img-fluid" alt="Marked">
            </a>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSite">
            <form class="form-inline mx-auto" >
              <input class="form-contro" type="search" placeholder="⠀Pesquisar...">
              <button class="btn btn-secondary" type="submit">ok</button>
            </form>

            <a href="safebox">
              <img src="../../public/img/pig.svg" class="pig" alt="Safebox">
            </a>

          </div>
        </div>
      </nav>

      <div class="sidebar">
        <header><div class="image"></div>Olá, <?=$user['user_name']?></header>
        <ul>
        <li><a href="myrequests"><img class="icon" src="../../public/img/myrequests.png">⠀Meus pedidos</a></li>
          <li><a href="make_order"><img class="icon" src="../../public/img/makeorder.png">⠀Fazer Pedido</a></li>
          <li><a href="notifications"><img class="icon" src="../../public/img/notification.png">⠀Notificações</a></li>
          <li><a href="profile"><img class="icon" src="../../public/img/myprofile.png">⠀Meu perfil</a></li>
          <li><a href="helpcenter"><img class="icon" src="../../public/img/helpcenter.png">⠀Central de ajuda</a></li>
          <li><a href="about_us"><img class="icon" src="../../public/img/aboutus.png">⠀Sobre nós</a></li>
          <li><a href="terms_of_use"><img class="icon" src="../../public/img/termsofuse.png">⠀Termos de uso</a></li>
          <li><a href="http://localhost:8080/login/logout"><img class="icon" src="../../public/img/logoff.svg">⠀Sair</a></li>
        </ul>
      </div>

      <div class="cofre">

        <h1 class="title">Meus pedidos</h1>
        
  <?php if(isset($makeOrder[0])){ ?>
          
          
            <div class="cont-cofre">
            <div class="card" style="width: 18rem;">
              <img src="../../<?=$makeOrder[0]['path_image']?>" class="card-img-top" alt="..."  height="150">
              <div class="card-body">
                <h5 class="card-title"><?=$makeOrder[0]['order_name']?></h5>
                <p class="card-text price">Preço disposto a pagar: <?=$makeOrder[0]['order_price']?></p>
                <p class="card-text">Categoria: <?=$makeOrder[0]['categories']?></p>
                <div class="card1">
                  <form  method="POST" action="/myrequests/edita">
                    <button href="/myrequests/edita"  class="btn btn-primary" name="edita" value="<?=$makeOrder[0]['order_name']?>">Editar</button>
                    <button href="/myrequests/edita" class="btn btn-primary" name="excluir" value="<?=$makeOrder[0]['id_order']?>">Excluir</button>
                  </form> 
                </div>
                <div class="card2">
                  <a href="#" class="btn btn-primary bt">Ver propostas para este pedido</a>
                </div>
              </div>
            </div>
        

          <?php if(isset($makeOrder[1])){ ?>

                  <div class="card" style="width: 18rem;">
                    <img src="../../<?=$makeOrder[1]['path_image']?>" class="card-img-top" alt="..."  height="150">
                    <div class="card-body">
                      <h5 class="card-title"><?=$makeOrder[1]['order_name']?></h5>
                      <p class="card-text price">Preço disposto a pagar: <?=$makeOrder[1]['order_price']?></p>
                      <p class="card-text">Categoria: <?=$makeOrder[1]['categories']?></p>
                      <div class="card1">
                      <form  method="POST" action="/myrequests/edita">
                    <button href="/myrequests/edita"  class="btn btn-primary" name="edita" value="<?=$makeOrder[1]['order_name']?>">Editar</button>
                    <button href="/myrequests/edita" class="btn btn-primary" name="excluir" value="<?=$makeOrder[1]['id_order']?>">Excluir</button>
                  </form> 
                      </div>
                      <div class="card2">
                        <a href="#" class="btn btn-primary bt">Ver propostas para este pedido</a>
                      </div>
                    </div>
                  </div>

                  <?php if(isset($makeOrder[2])){ ?>
                       
                    <div class="card" style="width: 18rem; ">
                          <img src="../../<?=$makeOrder[2]['path_image']?>" class="card-img-top" alt="..." height="150" width="42">
                          <div class="card-body">
                            <h5 class="card-title"><?=$makeOrder[2]['order_name']?></h5>
                            <p class="card-text price">Preço disposto a pagar:<?=$makeOrder[2]['order_price']?></p>
                            <p class="card-text">Categoria:<?=$makeOrder[2]['categories']?></p>
                          <div class="card1">
                          <form  method="POST" action="/myrequests/edita">
                            <button href="/myrequests/edita"  class="btn btn-primary" name="edita" value="<?=$makeOrder[2]['order_name']?>">Editar</button>
                            <button href="/myrequests/edita" class="btn btn-primary" name="excluir" value="<?=$makeOrder[2]['id_order']?>">Excluir</button>
                          </form> 
                          </div>
                          <div class="card2">
                            <a href="" class="btn btn-primary bt">Ver propostas para este pedido</a>
                          </div>
                        </div>
                      </div>

                      <?php if(isset($makeOrder[3])){ ?>
                        
                        <div class="card" style="width: 18rem;">
                          <img src="../../<?=$makeOrder[3]['path_image']?>" class="card-img-top" alt="..."  height="150">
                          <div class="card-body">
                            <h5 class="card-title"><?=$makeOrder[3]['order_name']?></h5>
                            <p class="card-text price">Preço disposto a pagar:  <?=$makeOrder[3]['order_price']?></p>
                            <p class="card-text">Categoria:  <?=$makeOrder[3]['categories']?></p>
                            <div class="card1">
                            <form  method="POST" action="/myrequests/edita">
                              <button href="/myrequests/edita"  class="btn btn-primary" name="edita" value="<?=$makeOrder[3]['order_name']?>">Editar</button>
                              <button href="/myrequests/edita" class="btn btn-primary" name="excluir" value="<?=$makeOrder[3]['id_order']?>">Excluir</button>
                            </form> 
                            </div>
                            <div class="card2">
                              <a href="#" class="btn btn-primary bt">Ver propostas para este pedido</a>
                            </div>
                          </div>
                        </div>
                        
                      <?php } ?>

                  <?php }?>

          <?php } ?>

<?php }else if(isset($edita)){ ?>
           
          <form  method="POST" action="/myrequests">
          <div class="card" style="width: 18rem;">
            <img src="../../<?=$makeOrder2[0]['path_image']?>" class="card-img-top" alt="..."  height="150">
            <div class="card-body">
              
              <input class="input2" name="order_name" value="<?=$makeOrder2[0]['order_name']?>">
                  Preço disposto a pagar: &nbsp;&nbsp;&nbsp; <input class="input" name="order_price" value="<?=$makeOrder2[0]['order_price']?>" >
                  Categoria: <input class="input3" name="categories" value="<?=$makeOrder2[0]['categories']?>" > 
              <br></br>
              <div class="card1">
             
                    <button    class="btn btn-primary" name="update" value="<?=$makeOrder2[0]['id_order']?>">Editar</button>
              </form>
              </div>
            </div>
          </div>



<? }else{ ?>
  <br></br>
  <br></br>
  <br></br>
  <br></br>
  <h5 style="text-align:center">Sem pedido</h5>
  
<?php } ?>         
 
        </div>
      </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="node_modules/jquery/dist/jquery.js"></script>
    <script src="node_modules/popper.js/dist/umd/popper.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.js"></script>
    
  </body>
</html>