<!doctype html>
<html lang="pt_br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="../../public/node_modules/bootstrap/compiler/bootstrap.css" rel="stylesheet">

    <link href="../../public/css/navbar.css" rel="stylesheet">
    <link rel="stylesheet" href="../../public/css/payment.css">
    <link rel="stylesheet" href="../../public/css/menu.css">

    <title>Marked</title>
  </head>
  <body>

    <input type="checkbox" id="check">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="log-men">
            <label for="check">
              <img src="../../public/img/menu.svg" id="btn"/>
            </label>
            <a href="index.html">
              <img src="../../public/img/logomarked.svg" class="img-fluid" alt="Marked">
            </a>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSite">
            <form class="form-inline mx-auto" >
              <input class="form-contro" type="search" placeholder="⠀Pesquisar...">
              <button class="btn btn-secondary" type="submit">ok</button>
            </form>

            <a href="safebox.html">
              <img src="../../public/img/pig.svg" class="pig" alt="Safebox">
            </a>

          </div>
        </div>
      </nav>

      <div class="sidebar">
        <header><div class="image"></div>Olá, ...</header>
        <ul>
          <li><a href="myrequests.html"><img class="icon" src="images/myrequests.png">⠀Meus pedidos</a></li>
          <li><a href="make_order.html"><img class="icon" src="images/makeorder.png">⠀Fazer Pedido</a></li>
          <li><a href="notifications.html"><img class="icon" src="images/notification.png">⠀Notificações</a></li>
          <li><a href="profile.html"><img class="icon" src="images/myprofile.png">⠀Meu perfil</a></li>
          <li><a href="helpcenter.html"><img class="icon" src="images/helpcenter.png">⠀Central de ajuda</a></li>
          <li><a href="about_us.html"><img class="icon" src="images/aboutus.png">⠀Sobre nós</a></li>
          <li><a href="terms_of_use.html"><img class="icon" src="images/termsofuse.png">⠀Termos de uso</a></li>
          <li><a href="#"><img class="icon" src="images/logoff.svg">⠀Sair</a></li>
        </ul>
      </div>

      <div class="cont">
        <div class="container_payment">
          <h1 class="title">Pagamento</h1>
          <span>Opções de entrega:</span>
          <div class="option">
            <input class="radio" type="radio">
            <p class="delivery">R$ 19,30 Entrega feita pela Fedex</p>
          </div>
          <div class="option">
            <input class="radio" type="radio">
            <p class="delivery">R$ 10,90 Entrega feita pelos Correios</p>
          </div>
          <hr>
          <span>Adicionar cartão de crédito:</span>
          <form class="credit_card" action="/purchase_confirmation" method="POST">
            <input class="credit" name="nome_cartao"type="text" placeholder="Nome no cartão">
            <input class="credit" name="numero_cartao"type="text" placeholder="Número do cartão">
            <input class="credit"  name="codigo_cartao" type="text" placeholder="Código de segurança (CVV)">
            <input class="credit" name="data_cartao"type="text" placeholder="Data de validade">
            <input class="confirm" type="submit" value="Confirmar">
          </form>
        </div>
      </div>



    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="node_modules/jquery/dist/jquery.js"></script>
    <script src="node_modules/popper.js/dist/umd/popper.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.js"></script>
    
  </body>
</html>