<!doctype html>
<html lang="pt_br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="../../public/node_modules/bootstrap/compiler/bootstrap.css" rel="stylesheet">

    <link href="../../public/css/navbar.css" rel="stylesheet">
    <link rel="stylesheet" href="../../public/css/view_more.css">
    <link rel="stylesheet" href="../../public/css/menu.css">

    <title>Marked</title>
  </head>
  <body>
          
    <input type="checkbox" id="check">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="log-men">
            <label for="check">
              <img src="../../public/img/menu.svg" id="btn"/>
            </label>
            <a href="indexMarked">
              <img src="../../public/img/logomarked.svg" class="img-fluid" alt="Marked">
            </a>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSite">
            <form class="form-inline mx-auto" >
              <input class="form-contro" type="search" placeholder="⠀Pesquisar...">
              <button class="btn btn-secondary" type="submit" onclick="window.location.href = 'make_proposal.html'">ok</button>
            </form>

            <a href="safebox">
              <img src="../../public/img/pig.svg" class="pig" alt="Safebox">
            </a>

          </div>
        </div>
      </nav>

      <div class="sidebar">
        <header><div class="image"></div>Olá, <?=$user['user_name']?></header>
        <ul>
          <li><a href="myrequests"><img class="icon" src="../../public/img/myrequests.png">⠀Meus pedidos</a></li>
          <li><a href="make_order"><img class="icon" src="../../public/img/makeorder.png">⠀Fazer Pedido</a></li>
          <li><a href="notifications"><img class="icon" src="../../public/img/notification.png">⠀Notificações</a></li>
          <li><a href="profile"><img class="icon" src="../../public/img/myprofile.png">⠀Meu perfil</a></li>
          <li><a href="helpcenter"><img class="icon" src="../../public/img/helpcenter.png">⠀Central de ajuda</a></li>
          <li><a href="about_us"><img class="icon" src="../../public/img/aboutus.png">⠀Sobre nós</a></li>
          <li><a href="terms_of_use"><img class="icon" src="../../public/img/termsofuse.png">⠀Termos de uso</a></li>
          <li><a href="http://localhost:8080/login/logout"><img class="icon" src="../../public/img/logoff.svg">⠀Sair</a></li>
        </ul>
      </div>
      <br>
      <h2 style="text-align:center">Propostas</h2>
            <hr>
      <div class="cont">
        <?php if(isset($record)){ ?>
          <div class="request">
            <br></br>
            <div class="img">
                <img  class="img-request" src="<?=$record[0]['path_image']?>" style="width:400px; height: 200px; text-align:center">
            </div>
            <div class="informations">
                <p class="label">Nome do produto: <?=$record[0]['proposal_name']?> </p>
                <p class="label">Usuario da proposta: <?=$user_proposal[0]['user_name']?></p>
                <p class="label">Valor da proposta: <?=$record[0]['proposal_price']?> </p>
                <p class="label">Quantidade: <?=$record[0]['proposal_amount']?> </p>
                
            </div>
            <form action="/address" method="POST">    
              <div class="center">
                  <button class="btn_make_proposal" href = 'address' name="make_proposal" value="">Aceitar</button>
                  <button class="btn_make_proposal_red" href = 'make_proposal' name="make_proposal" value="">Recusar</button>
              </div>
            </from> 
            <?php }else if(isset($sem_proposal)){ ?>
            
            <h3 style="text-align:center">Sem propostas</h3>
         <?php } ?>    
          </div>
         
      </div>
     

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="node_modules/jquery/dist/jquery.js"></script>
    <script src="node_modules/popper.js/dist/umd/popper.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.js"></script>
    
  </body>
</html>