<!doctype html>
<html lang="pt_br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="../../public/node_modules/bootstrap/compiler/bootstrap.css" rel="stylesheet">

    <link href="../../public/css/navbar.css" rel="stylesheet">
    <link rel="stylesheet" href="../../public/css/terms_of_use.css">
    <link rel="stylesheet" href="../../public/css/menu.css">

    <title>Marked</title>
  </head>
  <body>
          
    <input type="checkbox" id="check">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="log-men">
            <label for="check">
              <img src="../../public/img/menu.svg" id="btn"/>
            </label>
            <a href="indexMarked">
              <img src="../../public/img/logomarked.svg" class="img-fluid" alt="Marked">
            </a>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSite">
            <form class="form-inline mx-auto" >
              <input class="form-contro" type="search" placeholder="⠀Pesquisar...">
              <button class="btn btn-secondary" type="submit">ok</button>
            </form>

            <a href="safebox">
              <img src="../../public/img/pig.svg" class="pig" alt="Safebox">
            </a>

          </div>
        </div>
      </nav>

      <div class="sidebar">
        <header><div class="image"></div>Olá, <?=$user['user_name']?></header>
        <ul>
        <li><a href="myrequests"><img class="icon" src="../../public/img/myrequests.png">⠀Meus pedidos</a></li>
          <li><a href="make_order"><img class="icon" src="../../public/img/makeorder.png">⠀Fazer Pedido</a></li>
          <li><a href="notifications"><img class="icon" src="../../public/img/notification.png">⠀Notificações</a></li>
          <li><a href="profile"><img class="icon" src="../../public/img/myprofile.png">⠀Meu perfil</a></li>
          <li><a href="helpcenter"><img class="icon" src="../../public/img/helpcenter.png">⠀Central de ajuda</a></li>
          <li><a href="about_us"><img class="icon" src="../../public/img/aboutus.png">⠀Sobre nós</a></li>
          <li><a href="terms_of_use"><img class="icon" src="../../public/img/termsofuse.png">⠀Termos de uso</a></li>
          <li><a href="http://localhost:8080/login/logout"><img class="icon" src="../../public/img/logoff.svg">⠀Sair</a></li>
        </ul>
      </div>

      <div class="about">
        <div class="cont">
          <h1 class="title">Termos de uso</h1>

        
            <p>
                        
                      <p>1. Termos Ao acessar ao site Marked.com.br, concorda em cumprir estes termos de serviço, todas as leis e regulamentos aplicáveis e concorda que é responsável pelo cumprimento de todas as leis locais aplicáveis. Se você não concordar com algum desses termos, está proibido de usar ou acessar este site. Os materiais contidos neste site são protegidos pelas leis de direitos autorais e marcas comerciais aplicáveis.
                     </p>
                      <p>2.	Uso de Licença É concedida permissão para baixar temporariamente uma cópia dos materiais (informações ou software) no site Marked.com.br , apenas para visualização transitória pessoal e não comercial. Esta é a concessão de uma licença, não uma transferência de título e, sob esta licença, você não pode:
                      </p>  
                      
                     <p style="text-align:left"> 1.	modificar ou copiar os materiais;
                     </p>   
                     <p>  2.	usar os materiais para qualquer finalidade comercial ou para exibição pública (comercial ou não comercial);
                      </p>  
                      <p>  3.	tentar descompilar ou fazer engenharia reversa de qualquer software contido no site Marked.com.br;
                      </p>  
                      <p>  4.	remover quaisquer direitos autorais ou outras notações de propriedade dos materiais; ou
                      </p>  
                      <p>  5.	transferir os materiais para outra pessoa ou 'espelhe' os materiais em qualquer outro servidor Esta licença será automaticamente rescindida se você violar alguma dessas restrições e poderá ser rescindida por Marked.com.br a qualquer momento. Ao encerrar a visualização desses materiais ou após o término desta licença, você deve apagar todos os materiais baixados em sua posse, seja em formato eletrônico ou impresso.
                      </p>   
                      <p>  3. Isenção de responsabilidade
                      </p>   
                      <p>  1.	Os materiais no site da Marked.com.br são fornecidos 'como estão'. Marked.com.br não oferece garantias, expressas ou implícitas, e, por este meio, isenta e nega todas as outras garantias, incluindo, sem limitação, garantias implícitas ou condições de comercialização, adequação a um fim específico ou não violação de propriedade intelectual ou outra violação de direitos.
                      </p>   
                      <p>  2.	Além disso, o Marked.com.br não garante ou faz qualquer representação relativa à precisão, aos resultados prováveis ou à confiabilidade do uso dos materiais em seu site ou de outra forma relacionado a esses materiais ou em sites vinculados a este site.
                      </p>  
          <p>4. Limitações
                  Em nenhum caso o Marked.com.br ou seus fornecedores serão responsáveis por quaisquer danos (incluindo, sem limitação, danos por perda de dados ou lucro ou devido a interrupção dos negócios) decorrentes do uso ou da incapacidade de usar os materiais em Marked.com.br, mesmo que Marked.com.br ou um representante autorizado da Marked.com.br tenha sido notificado oralmente ou
                   por escrito da possibilidade de tais danos. Como algumas jurisdições não permitem limitações em garantias implícitas, ou limitações de responsabilidade por danos consequentes ou incidentais, essas limitações podem não se aplicar a você.
                   </p>  
                    <p>   5. Precisão dos materiais
                       Os materiais exibidos no site da Marked.com.br podem incluir erros técnicos, tipográficos ou fotográficos. Marked.com.br não garante que qualquer material em seu site seja preciso, completo ou atual. Marked.com.br pode fazer alterações nos materiais contidos em seu site a qualquer momento, sem aviso prévio. No entanto, Marked.com.br não se compromete a atualizar os materiais.
                       </p>  
          <p>6. Links O Marked.com.br não analisou todos os sites vinculados ao seu site e não é responsável pelo conteúdo de nenhum site vinculado. A inclusão de qualquer link não implica endosso por Marked.com.br do site. O uso de qualquer site vinculado é por conta e risco do usuário.
                 Modificações
                        O Marked.com.br pode revisar estes termos de serviço do site a qualquer momento, sem aviso prévio. Ao usar este site, você concorda em ficar vinculado à versão atual desses termos de serviço.
          Lei aplicável
                        Estes termos e condições são regidos e interpretados de acordo com as leis do Marked.com.br e você se submete irrevogavelmente à jurisdição exclusiva dos tribunais naquele estado ou localidade.
                        </p>  
            </p>
        
        </div>
      </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="node_modules/jquery/dist/jquery.js"></script>
    <script src="node_modules/popper.js/dist/umd/popper.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.js"></script>
    
  </body>
</html>